### ISSUE TITLE
oci-env can't mount files between host and container

### ISSUE THREAD

**Issue by decko** [pulp/oci_env#101]
## Description
When using the `volumes` directive on the `compose.yaml` file of a profile you can't use it to mount a host file into the container.

## How to reproduce
Create a new profile and in the `compose.yaml` file, create a new `services` entry, add a new `volumes` directive to it and try to mount or bind a file from the host to the container, like this:
```yaml
services:
    some_service:
        volumes:
            - ./a_local_file.yml:/etc/a_container_file.yml
```

## What is expected
You're expected to find that same file inside of the container, although you gonna find it mounted as an empty directory.

## Additional info
You can find under the `./compiled/oci_env` directory the directory with the same name of the file which was intended to be mounted into the container.
